config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }
  resources :users
  resources :news_sources
  resources :articles
  root to: 'articles#index'
  get 'news_fetchers/fetch_news', to: 'news_fetchers#fetch_news'
  get 'news_fetchers/fetch_sources', to: 'news_fetchers#fetch_sources'
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_one_attached :image
  validates :url, uniqueness: true
  validates :title, :url, :published_at, presence: true
  belongs_to :news_source
  scope :published_today, -> { where('articles.created_at >= ?', 1.day.ago) }
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @articles = authorize Article.all
    @articles = current_user.articles if current_user.present? && current_user.activated?
    @articles = @articles.order(published_at: :desc)
    @articles = @articles.paginate(page: params[:page], per_page: 5)
  end

  def show
    @article = Article.find(params[:id])
    authorize @article
  end

  def new
    @article = Article.new
    authorize @article
  end

  def edit
    @article = Article.find(params[:id])
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    authorize @article
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    authorize @article
    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.image.purge
    authorize @article
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:news_source_id, :title, :description, :url, :url_to_image,
                                    :published_at, :image)
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= bootstrap_form_for(@article) do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.collection_select(:news_source_id, NewsSource.all, :id, :name) %>
  </p>
  <%= form.text_field :title %>
  </p>
  <%= form.text_area :description %>
  <p>
    <%= form.text_field :url %>
  </p>
  <%= form.text_field :url_to_image %>
  <p>
    <%= form.date_field :published_at %>
  <p>
  <p>
    <%= form.file_field :image %>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path, class:"btn btn-sm btn-outline-secondary" %>

app/views/articles/index.html.erb
<div class="row">
      <div class = 'col-md-8 blog-main'>
        <div class="blog-post">
       <%  @articles.each do |article| %>
      <h4 class="blog-post-title">
        <%= link_to "#{article.title}", article_path(article), class: 'navbar-brand' %> </h4>
            <p class="blog-post-meta"><%= article.published_at.to_s(:custom_datetime) %> from
            <a href="<%= article.url %>"> <%= article.news_source.name %>  </a>
            </p>
            <hr>
            <p><%= article.description %> </p>
            <p><%= link_to (image_tag article.url_to_image, size: '500x300'), article_path(article)  unless article.url_to_image.blank? %> </p>
            <p><%= link_to (image_tag article.image, size: '500x300'), article_path(article) if article.image.attached? %> </p>
            <% if policy(@articles).update? %>
      <%= link_to 'Edit', edit_article_path(article), class:"btn btn-sm btn-outline-secondary" %>
            <%end %>
              <% if policy(@articles).destroy? %>
      <%= link_to 'Destroy', article_path(article),class:"btn btn-sm btn-outline-secondary",
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
            <%end %>
    <%end %>
      </div>
          <div class="page_info">
            <%= page_entries_info @articles %>
          </div>
           <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer , list_classes: %w(pagination justify-content-end) %>
        </div>
  <aside class="col-md-4 blog-sidebar">

    <% if policy(@articles).update? %>
   <%= link_to 'New Article', new_article_path, class:"btn btn-sm btn-outline-secondary"  %>
    <%end %>
    <% if policy(NewsSource).update? %>
    <%= link_to 'Sources', news_sources_path, class:"btn btn-sm btn-outline-secondary"  %>
    <%end %>
  </aside>
      </div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path, class:"btn btn-sm btn-outline-secondary" %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>
<p>
  <strong>Source:</strong>
<td><%= @article.news_source.name %></td>
</p>
<p><%= image_tag @article.url_to_image, size: '500x300' unless @article.url_to_image.blank? %> </p>
  <p>
  <%= image_tag @article.image, size: '500x300' if @article.image.attached?  %>
  </p>
<% if policy(@article).update? %>
<%= link_to 'Edit', edit_article_path(@article), class:"btn btn-sm btn-outline-secondary" %>
<%end %>
<%= link_to 'Back', articles_path, class:"btn btn-sm btn-outline-secondary" %>