config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }
  resources :users
  resources :news_sources
  resources :articles
  root to: 'articles#index'
  get 'news_fetchers/fetch_news', to: 'news_fetchers#fetch_news'
  get 'news_fetchers/fetch_sources', to: 'news_fetchers#fetch_sources'
end

app/models/news_source.rb
# frozen_string_literal: true

class NewsSource < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :articles, dependent: :destroy
  has_many :user_news_sources, dependent: :destroy
  has_many :users, through: :user_news_sources
end

app/controllers/news_sources_controller.rb
# frozen_string_literal: true

class NewsSourcesController < ApplicationController
  def index
    @news_sources = NewsSource.all
    authorize @news_sources
  end

  def show
    @news_source = NewsSource.find(params[:id])
    authorize @news_source
  end

  def new
    @news_source = NewsSource.new
    authorize @news_source
  end

  def edit
    @news_source = NewsSource.find(params[:id])
    authorize @news_source
  end

  def create
    @news_source = NewsSource.new(source_params)
    authorize @news_source
    if @news_source.save
      redirect_to news_sources_path
    else
      render 'new'
    end
  end

  def update
    @news_source = NewsSource.find(params[:id])
    authorize @news_source
    if @news_source.update(news_source_params)
      redirect_to news_source_params
    else
      render 'edit'
    end
  end

  def destroy
    @news_source = NewsSource.find(params[:id])
    authorize @news_source
    @news_source.destroy
    redirect_to news_sources_path
  end

  private

  def news_source_params
    params.require(:news_source).permit(:name)
  end
end

app/helpers/news_sources_helper.rb
# frozen_string_literal: true

module NewsSourcesHelper
end

app/views/news_sources/_form.html.erb
<%= bootstrap_form_for(@news_source) do |form| %>
  <% if @news_source.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@news_source.errors.count, "error") %> prohibited
        this source from being saved:
      </h2>
      <ul>
        <% @news_source.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </p>
  <%= form.text_field :name %>
  </p>
  <%= form.submit %>
  </p>
<% end %>

app/views/news_sources/edit.html.erb
<h1>Editing source</h1>
<%= render 'form' %>
<%= link_to 'Back', news_sources_path, class:"btn btn-sm btn-outline-secondary" %>

app/views/news_sources/index.html.erb
<h2>News Sources</h2>
<table>
  <tr>
    <th>Name</th>
    <th colspan="10"></th>
    <th colspan="10"></th>
  </tr>

  <tr>
    <%  @news_sources.each do |source| %>
      <td><%= source.name %></td>
      <td><%= link_to 'Show', news_source_path(source), class:"btn btn-sm btn-outline-secondary" %></td>
      <td> <%= link_to 'Edit', edit_news_source_path(source), class:"btn btn-sm btn-outline-secondary" %></td>
      <td><%= link_to 'Destroy', news_source_path(source), class:"btn btn-sm btn-outline-secondary",
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%end %>

    </table>
 <%= link_to 'New Source', new_news_source_path, class:"btn btn-sm btn-outline-secondary" %>

app/views/news_sources/new.html.erb
<h1>New Source</h1>
<%= render 'form' %>
<%= link_to 'Back', news_sources_path, class:"btn btn-sm btn-outline-secondary" %>

app/views/news_sources/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @news_source.name %>
</p>
<%= link_to 'Edit', edit_news_source_path(@news_source) , class:"btn btn-sm btn-outline-secondary" %>
<%= link_to 'Back', news_sources_path , class:"btn btn-sm btn-outline-secondary" %>